In [8]:
import sys
print(sys.executable)

/Applications/Xcode.app/Contents/Developer/usr/bin/python3

In [9]:
import numpy as np
import pandas as pd
import openpyxl

In [10]:
# string
country = ['India','Pakistan','USA','Nepal','Srilanka']

pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4    Srilanka
dtype: object

In [11]:
# integers
runs = [13,24,56,78,100]

runs_ser = pd.Series(runs)
runs_ser

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [12]:
# custom index
marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']

pd.Series(marks,index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [13]:
# setting a name
marks = pd.Series(marks,index=subjects,name='Nitish ke marks')
marks

maths       67
english     57
science     89
hindi      100
Name: Nitish ke marks, dtype: int64

In [14]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}

marks_series = pd.Series(marks,name='nitish ke marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: nitish ke marks, dtype: int64

In [15]:
# size
marks_series.size

4

In [16]:
# dtype
marks_series.dtype

dtype('int64')

In [17]:
# name
marks_series.name

'nitish ke marks'

In [18]:
# is_unique
marks_series.is_unique

pd.Series([1,1,2,3,4,5]).is_unique

False

In [19]:
# index
marks_series.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [20]:
marks_series.values

array([ 67,  57,  89, 100])

In [ ]:
vk=pd.read_csv('kohli_ipl.csv',squeezed=True)
vk

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [31]:
subs=pd.read_excel('subs.xlsx')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [33]:
movies= pd.read_excel('bollywood.xlsx')
movies

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [34]:
# head and tail
subs.head()

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [35]:
vk.head(3)

   match_no  runs
0         1     1
1         2    23
2         3    13

In [36]:
vk.tail(10)

     match_no  runs
205       206     0
206       207     0
207       208     9
208       209    58
209       210    30
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

In [37]:
# sample
movies.sample(5)

                                 movie               lead
802            Saheb Biwi Aur Gangster    Jimmy Sheirgill
307                 Sultan (2016 film)        Salman Khan
1118               Shakalaka Boom Boom         Bobby Deol
1471          Mumbai Se Aaya Mera Dost  Abhishek Bachchan
1120  Salaam-e-Ishq: A Tribute to Love        Salman Khan

In [38]:
# value_counts -> movies
movies.value_counts()

movie                     lead
Andaaz                    Akshay Kumar        2
Tanu Weds Manu: Returns   Kangana Ranaut      2
Gabbar Is Back            Akshay Kumar        2
1920 (film)               Rajniesh Duggall    1
Newton (film)             Rajkummar Rao       1
                                             ..
Ghayal: Once Again        Sunny Deol          1
Ghanchakkar (film)        Vidya Balan         1
Ghajini (2008 film)       Aamir Khan          1
Genius (2018 Hindi film)  Utkarsh Sharma      1
Zor Lagaa Ke...Haiya!     Meghan Jadhav       1
Name: count, Length: 1497, dtype: int64

In [47]:
# sort_values -> inplace
vk.sort_values(ascending=False).head(1).values[0]

TypeError: sort_values() missing 1 required positional argument: 'by'